#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataToDBCont
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BatteryCheckerDB2")]
	public partial class DataToDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertLogDetail(DataToDBEnts.LogDetail instance);
    partial void UpdateLogDetail(DataToDBEnts.LogDetail instance);
    partial void DeleteLogDetail(DataToDBEnts.LogDetail instance);
    partial void InsertParameter_Role(DataToDBEnts.Parameter_Role instance);
    partial void UpdateParameter_Role(DataToDBEnts.Parameter_Role instance);
    partial void DeleteParameter_Role(DataToDBEnts.Parameter_Role instance);
    partial void InsertParameter_Type(DataToDBEnts.Parameter_Type instance);
    partial void UpdateParameter_Type(DataToDBEnts.Parameter_Type instance);
    partial void DeleteParameter_Type(DataToDBEnts.Parameter_Type instance);
    partial void InsertParameter_User(DataToDBEnts.Parameter_User instance);
    partial void UpdateParameter_User(DataToDBEnts.Parameter_User instance);
    partial void DeleteParameter_User(DataToDBEnts.Parameter_User instance);
    partial void InsertProduction_Batch(DataToDBEnts.Production_Batch instance);
    partial void UpdateProduction_Batch(DataToDBEnts.Production_Batch instance);
    partial void DeleteProduction_Batch(DataToDBEnts.Production_Batch instance);
    partial void InsertProduction_Check(DataToDBEnts.Production_Check instance);
    partial void UpdateProduction_Check(DataToDBEnts.Production_Check instance);
    partial void DeleteProduction_Check(DataToDBEnts.Production_Check instance);
    #endregion
		
		public DataToDBDataContext() : 
				base(global::MaterialHandling.Properties.Settings.Default.BatteryCheckerDB2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataToDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataToDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataToDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataToDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DataToDBEnts.LogDetail> LogDetail
		{
			get
			{
				return this.GetTable<DataToDBEnts.LogDetail>();
			}
		}
		
		public System.Data.Linq.Table<DataToDBEnts.Parameter_Role> Parameter_Role
		{
			get
			{
				return this.GetTable<DataToDBEnts.Parameter_Role>();
			}
		}
		
		public System.Data.Linq.Table<DataToDBEnts.Parameter_Type> Parameter_Type
		{
			get
			{
				return this.GetTable<DataToDBEnts.Parameter_Type>();
			}
		}
		
		public System.Data.Linq.Table<DataToDBEnts.Parameter_User> Parameter_User
		{
			get
			{
				return this.GetTable<DataToDBEnts.Parameter_User>();
			}
		}
		
		public System.Data.Linq.Table<DataToDBEnts.Production_Batch> Production_Batch
		{
			get
			{
				return this.GetTable<DataToDBEnts.Production_Batch>();
			}
		}
		
		public System.Data.Linq.Table<DataToDBEnts.Production_Check> Production_Check
		{
			get
			{
				return this.GetTable<DataToDBEnts.Production_Check>();
			}
		}
	}
}
namespace DataToDBEnts
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogDetail")]
	public partial class LogDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _LogID;
		
		private System.Nullable<System.DateTime> _LogDate;
		
		private string _LogLevel;
		
		private string _LogThread;
		
		private string _Logger;
		
		private string _ActionType;
		
		private string _LogMessage;
		
		private string _UsName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIDChanging(System.Guid value);
    partial void OnLogIDChanged();
    partial void OnLogDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLogDateChanged();
    partial void OnLogLevelChanging(string value);
    partial void OnLogLevelChanged();
    partial void OnLogThreadChanging(string value);
    partial void OnLogThreadChanged();
    partial void OnLoggerChanging(string value);
    partial void OnLoggerChanged();
    partial void OnActionTypeChanging(string value);
    partial void OnActionTypeChanged();
    partial void OnLogMessageChanging(string value);
    partial void OnLogMessageChanged();
    partial void OnUsNameChanging(string value);
    partial void OnUsNameChanged();
    #endregion
		
		public LogDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid LogID
		{
			get
			{
				return this._LogID;
			}
			set
			{
				if ((this._LogID != value))
				{
					this.OnLogIDChanging(value);
					this.SendPropertyChanging();
					this._LogID = value;
					this.SendPropertyChanged("LogID");
					this.OnLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this.OnLogDateChanging(value);
					this.SendPropertyChanging();
					this._LogDate = value;
					this.SendPropertyChanged("LogDate");
					this.OnLogDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogLevel", DbType="NVarChar(10)")]
		public string LogLevel
		{
			get
			{
				return this._LogLevel;
			}
			set
			{
				if ((this._LogLevel != value))
				{
					this.OnLogLevelChanging(value);
					this.SendPropertyChanging();
					this._LogLevel = value;
					this.SendPropertyChanged("LogLevel");
					this.OnLogLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogThread", DbType="NVarChar(10)")]
		public string LogThread
		{
			get
			{
				return this._LogThread;
			}
			set
			{
				if ((this._LogThread != value))
				{
					this.OnLogThreadChanging(value);
					this.SendPropertyChanging();
					this._LogThread = value;
					this.SendPropertyChanged("LogThread");
					this.OnLogThreadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logger", DbType="NVarChar(50)")]
		public string Logger
		{
			get
			{
				return this._Logger;
			}
			set
			{
				if ((this._Logger != value))
				{
					this.OnLoggerChanging(value);
					this.SendPropertyChanging();
					this._Logger = value;
					this.SendPropertyChanged("Logger");
					this.OnLoggerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionType", DbType="NVarChar(50)")]
		public string ActionType
		{
			get
			{
				return this._ActionType;
			}
			set
			{
				if ((this._ActionType != value))
				{
					this.OnActionTypeChanging(value);
					this.SendPropertyChanging();
					this._ActionType = value;
					this.SendPropertyChanged("ActionType");
					this.OnActionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogMessage", DbType="NVarChar(3000)")]
		public string LogMessage
		{
			get
			{
				return this._LogMessage;
			}
			set
			{
				if ((this._LogMessage != value))
				{
					this.OnLogMessageChanging(value);
					this.SendPropertyChanging();
					this._LogMessage = value;
					this.SendPropertyChanged("LogMessage");
					this.OnLogMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsName", DbType="NVarChar(50)")]
		public string UsName
		{
			get
			{
				return this._UsName;
			}
			set
			{
				if ((this._UsName != value))
				{
					this.OnUsNameChanging(value);
					this.SendPropertyChanging();
					this._UsName = value;
					this.SendPropertyChanged("UsName");
					this.OnUsNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parameter_Role")]
	public partial class Parameter_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoleID;
		
		private string _Role_Name;
		
		private string _Authority;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoleIDChanging(int value);
    partial void OnRoleIDChanged();
    partial void OnRole_NameChanging(string value);
    partial void OnRole_NameChanged();
    partial void OnAuthorityChanging(string value);
    partial void OnAuthorityChanged();
    #endregion
		
		public Parameter_Role()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Role_Name
		{
			get
			{
				return this._Role_Name;
			}
			set
			{
				if ((this._Role_Name != value))
				{
					this.OnRole_NameChanging(value);
					this.SendPropertyChanging();
					this._Role_Name = value;
					this.SendPropertyChanged("Role_Name");
					this.OnRole_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Authority", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Authority
		{
			get
			{
				return this._Authority;
			}
			set
			{
				if ((this._Authority != value))
				{
					this.OnAuthorityChanging(value);
					this.SendPropertyChanging();
					this._Authority = value;
					this.SendPropertyChanged("Authority");
					this.OnAuthorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parameter_Type")]
	public partial class Parameter_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _typeid;
		
		private string _ModelID;
		
		private string _TypeName;
		
		private float _Voltage_Standard_Value;
		
		private float _Voltage_Max;
		
		private float _Voltage_Min;
		
		private float _U_Phase_Impairment;
		
		private float _Resistance_Standard_Value;
		
		private float _Resistance_Max;
		
		private float _Resistance_Min;
		
		private float _R_Phase_Impairment;
		
		private float _coefficient;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntypeidChanging(int value);
    partial void OntypeidChanged();
    partial void OnModelIDChanging(string value);
    partial void OnModelIDChanged();
    partial void OnTypeNameChanging(string value);
    partial void OnTypeNameChanged();
    partial void OnVoltage_Standard_ValueChanging(float value);
    partial void OnVoltage_Standard_ValueChanged();
    partial void OnVoltage_MaxChanging(float value);
    partial void OnVoltage_MaxChanged();
    partial void OnVoltage_MinChanging(float value);
    partial void OnVoltage_MinChanged();
    partial void OnU_Phase_ImpairmentChanging(float value);
    partial void OnU_Phase_ImpairmentChanged();
    partial void OnResistance_Standard_ValueChanging(float value);
    partial void OnResistance_Standard_ValueChanged();
    partial void OnResistance_MaxChanging(float value);
    partial void OnResistance_MaxChanged();
    partial void OnResistance_MinChanging(float value);
    partial void OnResistance_MinChanged();
    partial void OnR_Phase_ImpairmentChanging(float value);
    partial void OnR_Phase_ImpairmentChanged();
    partial void OncoefficientChanging(float value);
    partial void OncoefficientChanged();
    #endregion
		
		public Parameter_Type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int typeid
		{
			get
			{
				return this._typeid;
			}
			set
			{
				if ((this._typeid != value))
				{
					this.OntypeidChanging(value);
					this.SendPropertyChanging();
					this._typeid = value;
					this.SendPropertyChanged("typeid");
					this.OntypeidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this.OnModelIDChanging(value);
					this.SendPropertyChanging();
					this._ModelID = value;
					this.SendPropertyChanged("ModelID");
					this.OnModelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TypeName
		{
			get
			{
				return this._TypeName;
			}
			set
			{
				if ((this._TypeName != value))
				{
					this.OnTypeNameChanging(value);
					this.SendPropertyChanging();
					this._TypeName = value;
					this.SendPropertyChanged("TypeName");
					this.OnTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Standard_Value", DbType="Real NOT NULL")]
		public float Voltage_Standard_Value
		{
			get
			{
				return this._Voltage_Standard_Value;
			}
			set
			{
				if ((this._Voltage_Standard_Value != value))
				{
					this.OnVoltage_Standard_ValueChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Standard_Value = value;
					this.SendPropertyChanged("Voltage_Standard_Value");
					this.OnVoltage_Standard_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Max", DbType="Real NOT NULL")]
		public float Voltage_Max
		{
			get
			{
				return this._Voltage_Max;
			}
			set
			{
				if ((this._Voltage_Max != value))
				{
					this.OnVoltage_MaxChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Max = value;
					this.SendPropertyChanged("Voltage_Max");
					this.OnVoltage_MaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Min", DbType="Real NOT NULL")]
		public float Voltage_Min
		{
			get
			{
				return this._Voltage_Min;
			}
			set
			{
				if ((this._Voltage_Min != value))
				{
					this.OnVoltage_MinChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Min = value;
					this.SendPropertyChanged("Voltage_Min");
					this.OnVoltage_MinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_Phase_Impairment", DbType="Real NOT NULL")]
		public float U_Phase_Impairment
		{
			get
			{
				return this._U_Phase_Impairment;
			}
			set
			{
				if ((this._U_Phase_Impairment != value))
				{
					this.OnU_Phase_ImpairmentChanging(value);
					this.SendPropertyChanging();
					this._U_Phase_Impairment = value;
					this.SendPropertyChanged("U_Phase_Impairment");
					this.OnU_Phase_ImpairmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Standard_Value", DbType="Real NOT NULL")]
		public float Resistance_Standard_Value
		{
			get
			{
				return this._Resistance_Standard_Value;
			}
			set
			{
				if ((this._Resistance_Standard_Value != value))
				{
					this.OnResistance_Standard_ValueChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Standard_Value = value;
					this.SendPropertyChanged("Resistance_Standard_Value");
					this.OnResistance_Standard_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Max", DbType="Real NOT NULL")]
		public float Resistance_Max
		{
			get
			{
				return this._Resistance_Max;
			}
			set
			{
				if ((this._Resistance_Max != value))
				{
					this.OnResistance_MaxChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Max = value;
					this.SendPropertyChanged("Resistance_Max");
					this.OnResistance_MaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Min", DbType="Real NOT NULL")]
		public float Resistance_Min
		{
			get
			{
				return this._Resistance_Min;
			}
			set
			{
				if ((this._Resistance_Min != value))
				{
					this.OnResistance_MinChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Min = value;
					this.SendPropertyChanged("Resistance_Min");
					this.OnResistance_MinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Phase_Impairment", DbType="Real NOT NULL")]
		public float R_Phase_Impairment
		{
			get
			{
				return this._R_Phase_Impairment;
			}
			set
			{
				if ((this._R_Phase_Impairment != value))
				{
					this.OnR_Phase_ImpairmentChanging(value);
					this.SendPropertyChanging();
					this._R_Phase_Impairment = value;
					this.SendPropertyChanged("R_Phase_Impairment");
					this.OnR_Phase_ImpairmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coefficient", DbType="Real NOT NULL")]
		public float coefficient
		{
			get
			{
				return this._coefficient;
			}
			set
			{
				if ((this._coefficient != value))
				{
					this.OncoefficientChanging(value);
					this.SendPropertyChanging();
					this._coefficient = value;
					this.SendPropertyChanged("coefficient");
					this.OncoefficientChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parameter_User")]
	public partial class Parameter_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Role_Name;
		
		private string _Password;
		
		private bool _Flag_Isvalid;
		
		private string _True_Name;
		
		private System.DateTime _Last_Login_Time;
		
		private System.DateTime _Try_Login_Time;
		
		private int _TryLoginCount;
		
		private string _RoleID;
		
		private string _Authority;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnRole_NameChanging(string value);
    partial void OnRole_NameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFlag_IsvalidChanging(bool value);
    partial void OnFlag_IsvalidChanged();
    partial void OnTrue_NameChanging(string value);
    partial void OnTrue_NameChanged();
    partial void OnLast_Login_TimeChanging(System.DateTime value);
    partial void OnLast_Login_TimeChanged();
    partial void OnTry_Login_TimeChanging(System.DateTime value);
    partial void OnTry_Login_TimeChanged();
    partial void OnTryLoginCountChanging(int value);
    partial void OnTryLoginCountChanged();
    partial void OnRoleIDChanging(string value);
    partial void OnRoleIDChanged();
    partial void OnAuthorityChanging(string value);
    partial void OnAuthorityChanged();
    #endregion
		
		public Parameter_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Role_Name
		{
			get
			{
				return this._Role_Name;
			}
			set
			{
				if ((this._Role_Name != value))
				{
					this.OnRole_NameChanging(value);
					this.SendPropertyChanging();
					this._Role_Name = value;
					this.SendPropertyChanged("Role_Name");
					this.OnRole_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag_Isvalid", DbType="Bit NOT NULL")]
		public bool Flag_Isvalid
		{
			get
			{
				return this._Flag_Isvalid;
			}
			set
			{
				if ((this._Flag_Isvalid != value))
				{
					this.OnFlag_IsvalidChanging(value);
					this.SendPropertyChanging();
					this._Flag_Isvalid = value;
					this.SendPropertyChanged("Flag_Isvalid");
					this.OnFlag_IsvalidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_True_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string True_Name
		{
			get
			{
				return this._True_Name;
			}
			set
			{
				if ((this._True_Name != value))
				{
					this.OnTrue_NameChanging(value);
					this.SendPropertyChanging();
					this._True_Name = value;
					this.SendPropertyChanged("True_Name");
					this.OnTrue_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Login_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Last_Login_Time
		{
			get
			{
				return this._Last_Login_Time;
			}
			set
			{
				if ((this._Last_Login_Time != value))
				{
					this.OnLast_Login_TimeChanging(value);
					this.SendPropertyChanging();
					this._Last_Login_Time = value;
					this.SendPropertyChanged("Last_Login_Time");
					this.OnLast_Login_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Try_Login_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Try_Login_Time
		{
			get
			{
				return this._Try_Login_Time;
			}
			set
			{
				if ((this._Try_Login_Time != value))
				{
					this.OnTry_Login_TimeChanging(value);
					this.SendPropertyChanging();
					this._Try_Login_Time = value;
					this.SendPropertyChanged("Try_Login_Time");
					this.OnTry_Login_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TryLoginCount", DbType="Int NOT NULL")]
		public int TryLoginCount
		{
			get
			{
				return this._TryLoginCount;
			}
			set
			{
				if ((this._TryLoginCount != value))
				{
					this.OnTryLoginCountChanging(value);
					this.SendPropertyChanging();
					this._TryLoginCount = value;
					this.SendPropertyChanged("TryLoginCount");
					this.OnTryLoginCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this.OnRoleIDChanging(value);
					this.SendPropertyChanging();
					this._RoleID = value;
					this.SendPropertyChanged("RoleID");
					this.OnRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Authority", DbType="NVarChar(50)")]
		public string Authority
		{
			get
			{
				return this._Authority;
			}
			set
			{
				if ((this._Authority != value))
				{
					this.OnAuthorityChanging(value);
					this.SendPropertyChanging();
					this._Authority = value;
					this.SendPropertyChanged("Authority");
					this.OnAuthorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Production_Batch")]
	public partial class Production_Batch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _GUID;
		
		private string _ModelID;
		
		private System.DateTime _Start_Time;
		
		private System.DateTime _Finish_Charging_Time;
		
		private string _Invoice_No;
		
		private string _Contract_No;
		
		private string _Batch_No;
		
		private int _Battery_Amount;
		
		private int _Serial_Number;
		
		private int _Actual_Detection_Amount;
		
		private System.Nullable<int> _Station_Address;
		
		private int _Algorithm;
		
		private float _Voltage_Max;
		
		private float _Voltage_Min;
		
		private float _Voltage_Avg;
		
		private float _Voltage_Dev;
		
		private float _Voltage_Up;
		
		private float _Voltage_Lower;
		
		private float _Resistance_Max;
		
		private float _Resistance_Min;
		
		private float _Resistance_Avg;
		
		private float _Resistance_Dev;
		
		private float _Resistance_Up;
		
		private float _Resistance_Lower;
		
		private int _Valid_Number;
		
		private int _Normal_Number;
		
		private int _V_Lower_Number;
		
		private int _V_UP_Number;
		
		private int _R_Lower_Number;
		
		private int _R_UP_Number;
		
		private string _UserID;
		
		private string _Material_Number;
		
		private string _description;
		
		private System.Nullable<int> _typeID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGUIDChanging(System.Guid value);
    partial void OnGUIDChanged();
    partial void OnModelIDChanging(string value);
    partial void OnModelIDChanged();
    partial void OnStart_TimeChanging(System.DateTime value);
    partial void OnStart_TimeChanged();
    partial void OnFinish_Charging_TimeChanging(System.DateTime value);
    partial void OnFinish_Charging_TimeChanged();
    partial void OnInvoice_NoChanging(string value);
    partial void OnInvoice_NoChanged();
    partial void OnContract_NoChanging(string value);
    partial void OnContract_NoChanged();
    partial void OnBatch_NoChanging(string value);
    partial void OnBatch_NoChanged();
    partial void OnBattery_AmountChanging(int value);
    partial void OnBattery_AmountChanged();
    partial void OnSerial_NumberChanging(int value);
    partial void OnSerial_NumberChanged();
    partial void OnActual_Detection_AmountChanging(int value);
    partial void OnActual_Detection_AmountChanged();
    partial void OnStation_AddressChanging(System.Nullable<int> value);
    partial void OnStation_AddressChanged();
    partial void OnAlgorithmChanging(int value);
    partial void OnAlgorithmChanged();
    partial void OnVoltage_MaxChanging(float value);
    partial void OnVoltage_MaxChanged();
    partial void OnVoltage_MinChanging(float value);
    partial void OnVoltage_MinChanged();
    partial void OnVoltage_AvgChanging(float value);
    partial void OnVoltage_AvgChanged();
    partial void OnVoltage_DevChanging(float value);
    partial void OnVoltage_DevChanged();
    partial void OnVoltage_UpChanging(float value);
    partial void OnVoltage_UpChanged();
    partial void OnVoltage_LowerChanging(float value);
    partial void OnVoltage_LowerChanged();
    partial void OnResistance_MaxChanging(float value);
    partial void OnResistance_MaxChanged();
    partial void OnResistance_MinChanging(float value);
    partial void OnResistance_MinChanged();
    partial void OnResistance_AvgChanging(float value);
    partial void OnResistance_AvgChanged();
    partial void OnResistance_DevChanging(float value);
    partial void OnResistance_DevChanged();
    partial void OnResistance_UpChanging(float value);
    partial void OnResistance_UpChanged();
    partial void OnResistance_LowerChanging(float value);
    partial void OnResistance_LowerChanged();
    partial void OnValid_NumberChanging(int value);
    partial void OnValid_NumberChanged();
    partial void OnNormal_NumberChanging(int value);
    partial void OnNormal_NumberChanged();
    partial void OnV_Lower_NumberChanging(int value);
    partial void OnV_Lower_NumberChanged();
    partial void OnV_UP_NumberChanging(int value);
    partial void OnV_UP_NumberChanged();
    partial void OnR_Lower_NumberChanging(int value);
    partial void OnR_Lower_NumberChanged();
    partial void OnR_UP_NumberChanging(int value);
    partial void OnR_UP_NumberChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnMaterial_NumberChanging(string value);
    partial void OnMaterial_NumberChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OntypeIDChanging(System.Nullable<int> value);
    partial void OntypeIDChanged();
    #endregion
		
		public Production_Batch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModelID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModelID
		{
			get
			{
				return this._ModelID;
			}
			set
			{
				if ((this._ModelID != value))
				{
					this.OnModelIDChanging(value);
					this.SendPropertyChanging();
					this._ModelID = value;
					this.SendPropertyChanged("ModelID");
					this.OnModelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this.OnStart_TimeChanging(value);
					this.SendPropertyChanging();
					this._Start_Time = value;
					this.SendPropertyChanged("Start_Time");
					this.OnStart_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finish_Charging_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Finish_Charging_Time
		{
			get
			{
				return this._Finish_Charging_Time;
			}
			set
			{
				if ((this._Finish_Charging_Time != value))
				{
					this.OnFinish_Charging_TimeChanging(value);
					this.SendPropertyChanging();
					this._Finish_Charging_Time = value;
					this.SendPropertyChanged("Finish_Charging_Time");
					this.OnFinish_Charging_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoice_No", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Invoice_No
		{
			get
			{
				return this._Invoice_No;
			}
			set
			{
				if ((this._Invoice_No != value))
				{
					this.OnInvoice_NoChanging(value);
					this.SendPropertyChanging();
					this._Invoice_No = value;
					this.SendPropertyChanged("Invoice_No");
					this.OnInvoice_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contract_No", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Contract_No
		{
			get
			{
				return this._Contract_No;
			}
			set
			{
				if ((this._Contract_No != value))
				{
					this.OnContract_NoChanging(value);
					this.SendPropertyChanging();
					this._Contract_No = value;
					this.SendPropertyChanged("Contract_No");
					this.OnContract_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Batch_No", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Batch_No
		{
			get
			{
				return this._Batch_No;
			}
			set
			{
				if ((this._Batch_No != value))
				{
					this.OnBatch_NoChanging(value);
					this.SendPropertyChanging();
					this._Batch_No = value;
					this.SendPropertyChanged("Batch_No");
					this.OnBatch_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery_Amount", DbType="Int NOT NULL")]
		public int Battery_Amount
		{
			get
			{
				return this._Battery_Amount;
			}
			set
			{
				if ((this._Battery_Amount != value))
				{
					this.OnBattery_AmountChanging(value);
					this.SendPropertyChanging();
					this._Battery_Amount = value;
					this.SendPropertyChanged("Battery_Amount");
					this.OnBattery_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serial_Number", DbType="Int NOT NULL")]
		public int Serial_Number
		{
			get
			{
				return this._Serial_Number;
			}
			set
			{
				if ((this._Serial_Number != value))
				{
					this.OnSerial_NumberChanging(value);
					this.SendPropertyChanging();
					this._Serial_Number = value;
					this.SendPropertyChanged("Serial_Number");
					this.OnSerial_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Actual_Detection_Amount", DbType="Int NOT NULL")]
		public int Actual_Detection_Amount
		{
			get
			{
				return this._Actual_Detection_Amount;
			}
			set
			{
				if ((this._Actual_Detection_Amount != value))
				{
					this.OnActual_Detection_AmountChanging(value);
					this.SendPropertyChanging();
					this._Actual_Detection_Amount = value;
					this.SendPropertyChanged("Actual_Detection_Amount");
					this.OnActual_Detection_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Station_Address", DbType="Int")]
		public System.Nullable<int> Station_Address
		{
			get
			{
				return this._Station_Address;
			}
			set
			{
				if ((this._Station_Address != value))
				{
					this.OnStation_AddressChanging(value);
					this.SendPropertyChanging();
					this._Station_Address = value;
					this.SendPropertyChanged("Station_Address");
					this.OnStation_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Algorithm", DbType="Int NOT NULL")]
		public int Algorithm
		{
			get
			{
				return this._Algorithm;
			}
			set
			{
				if ((this._Algorithm != value))
				{
					this.OnAlgorithmChanging(value);
					this.SendPropertyChanging();
					this._Algorithm = value;
					this.SendPropertyChanged("Algorithm");
					this.OnAlgorithmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Max", DbType="Real NOT NULL")]
		public float Voltage_Max
		{
			get
			{
				return this._Voltage_Max;
			}
			set
			{
				if ((this._Voltage_Max != value))
				{
					this.OnVoltage_MaxChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Max = value;
					this.SendPropertyChanged("Voltage_Max");
					this.OnVoltage_MaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Min", DbType="Real NOT NULL")]
		public float Voltage_Min
		{
			get
			{
				return this._Voltage_Min;
			}
			set
			{
				if ((this._Voltage_Min != value))
				{
					this.OnVoltage_MinChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Min = value;
					this.SendPropertyChanged("Voltage_Min");
					this.OnVoltage_MinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Avg", DbType="Real NOT NULL")]
		public float Voltage_Avg
		{
			get
			{
				return this._Voltage_Avg;
			}
			set
			{
				if ((this._Voltage_Avg != value))
				{
					this.OnVoltage_AvgChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Avg = value;
					this.SendPropertyChanged("Voltage_Avg");
					this.OnVoltage_AvgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Dev", DbType="Real NOT NULL")]
		public float Voltage_Dev
		{
			get
			{
				return this._Voltage_Dev;
			}
			set
			{
				if ((this._Voltage_Dev != value))
				{
					this.OnVoltage_DevChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Dev = value;
					this.SendPropertyChanged("Voltage_Dev");
					this.OnVoltage_DevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Up", DbType="Real NOT NULL")]
		public float Voltage_Up
		{
			get
			{
				return this._Voltage_Up;
			}
			set
			{
				if ((this._Voltage_Up != value))
				{
					this.OnVoltage_UpChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Up = value;
					this.SendPropertyChanged("Voltage_Up");
					this.OnVoltage_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Lower", DbType="Real NOT NULL")]
		public float Voltage_Lower
		{
			get
			{
				return this._Voltage_Lower;
			}
			set
			{
				if ((this._Voltage_Lower != value))
				{
					this.OnVoltage_LowerChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Lower = value;
					this.SendPropertyChanged("Voltage_Lower");
					this.OnVoltage_LowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Max", DbType="Real NOT NULL")]
		public float Resistance_Max
		{
			get
			{
				return this._Resistance_Max;
			}
			set
			{
				if ((this._Resistance_Max != value))
				{
					this.OnResistance_MaxChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Max = value;
					this.SendPropertyChanged("Resistance_Max");
					this.OnResistance_MaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Min", DbType="Real NOT NULL")]
		public float Resistance_Min
		{
			get
			{
				return this._Resistance_Min;
			}
			set
			{
				if ((this._Resistance_Min != value))
				{
					this.OnResistance_MinChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Min = value;
					this.SendPropertyChanged("Resistance_Min");
					this.OnResistance_MinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Avg", DbType="Real NOT NULL")]
		public float Resistance_Avg
		{
			get
			{
				return this._Resistance_Avg;
			}
			set
			{
				if ((this._Resistance_Avg != value))
				{
					this.OnResistance_AvgChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Avg = value;
					this.SendPropertyChanged("Resistance_Avg");
					this.OnResistance_AvgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Dev", DbType="Real NOT NULL")]
		public float Resistance_Dev
		{
			get
			{
				return this._Resistance_Dev;
			}
			set
			{
				if ((this._Resistance_Dev != value))
				{
					this.OnResistance_DevChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Dev = value;
					this.SendPropertyChanged("Resistance_Dev");
					this.OnResistance_DevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Up", DbType="Real NOT NULL")]
		public float Resistance_Up
		{
			get
			{
				return this._Resistance_Up;
			}
			set
			{
				if ((this._Resistance_Up != value))
				{
					this.OnResistance_UpChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Up = value;
					this.SendPropertyChanged("Resistance_Up");
					this.OnResistance_UpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Lower", DbType="Real NOT NULL")]
		public float Resistance_Lower
		{
			get
			{
				return this._Resistance_Lower;
			}
			set
			{
				if ((this._Resistance_Lower != value))
				{
					this.OnResistance_LowerChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Lower = value;
					this.SendPropertyChanged("Resistance_Lower");
					this.OnResistance_LowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valid_Number", DbType="Int NOT NULL")]
		public int Valid_Number
		{
			get
			{
				return this._Valid_Number;
			}
			set
			{
				if ((this._Valid_Number != value))
				{
					this.OnValid_NumberChanging(value);
					this.SendPropertyChanging();
					this._Valid_Number = value;
					this.SendPropertyChanged("Valid_Number");
					this.OnValid_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Normal_Number", DbType="Int NOT NULL")]
		public int Normal_Number
		{
			get
			{
				return this._Normal_Number;
			}
			set
			{
				if ((this._Normal_Number != value))
				{
					this.OnNormal_NumberChanging(value);
					this.SendPropertyChanging();
					this._Normal_Number = value;
					this.SendPropertyChanged("Normal_Number");
					this.OnNormal_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_Lower_Number", DbType="Int NOT NULL")]
		public int V_Lower_Number
		{
			get
			{
				return this._V_Lower_Number;
			}
			set
			{
				if ((this._V_Lower_Number != value))
				{
					this.OnV_Lower_NumberChanging(value);
					this.SendPropertyChanging();
					this._V_Lower_Number = value;
					this.SendPropertyChanged("V_Lower_Number");
					this.OnV_Lower_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_V_UP_Number", DbType="Int NOT NULL")]
		public int V_UP_Number
		{
			get
			{
				return this._V_UP_Number;
			}
			set
			{
				if ((this._V_UP_Number != value))
				{
					this.OnV_UP_NumberChanging(value);
					this.SendPropertyChanging();
					this._V_UP_Number = value;
					this.SendPropertyChanged("V_UP_Number");
					this.OnV_UP_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_Lower_Number", DbType="Int NOT NULL")]
		public int R_Lower_Number
		{
			get
			{
				return this._R_Lower_Number;
			}
			set
			{
				if ((this._R_Lower_Number != value))
				{
					this.OnR_Lower_NumberChanging(value);
					this.SendPropertyChanging();
					this._R_Lower_Number = value;
					this.SendPropertyChanged("R_Lower_Number");
					this.OnR_Lower_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R_UP_Number", DbType="Int NOT NULL")]
		public int R_UP_Number
		{
			get
			{
				return this._R_UP_Number;
			}
			set
			{
				if ((this._R_UP_Number != value))
				{
					this.OnR_UP_NumberChanging(value);
					this.SendPropertyChanging();
					this._R_UP_Number = value;
					this.SendPropertyChanged("R_UP_Number");
					this.OnR_UP_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Material_Number", DbType="NVarChar(300)")]
		public string Material_Number
		{
			get
			{
				return this._Material_Number;
			}
			set
			{
				if ((this._Material_Number != value))
				{
					this.OnMaterial_NumberChanging(value);
					this.SendPropertyChanging();
					this._Material_Number = value;
					this.SendPropertyChanged("Material_Number");
					this.OnMaterial_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(300)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeID", DbType="Int")]
		public System.Nullable<int> typeID
		{
			get
			{
				return this._typeID;
			}
			set
			{
				if ((this._typeID != value))
				{
					this.OntypeIDChanging(value);
					this.SendPropertyChanging();
					this._typeID = value;
					this.SendPropertyChanged("typeID");
					this.OntypeIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Production_Check")]
	public partial class Production_Check : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _GUID;
		
		private string _BatchID;
		
		private float _Open_Voltage;
		
		private System.DateTime _Test_Time;
		
		private int _Flag;
		
		private float _Voltage_Standard_Value;
		
		private int _Number;
		
		private float _Temperature;
		
		private int _Station_Address;
		
		private float _Resistance_Standard_Value;
		
		private float _Open_Resistance;
		
		private string _Battery_Serial_No;
		
		private string _Battery_P1;
		
		private string _Battery_P2;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGUIDChanging(System.Guid value);
    partial void OnGUIDChanged();
    partial void OnBatchIDChanging(string value);
    partial void OnBatchIDChanged();
    partial void OnOpen_VoltageChanging(float value);
    partial void OnOpen_VoltageChanged();
    partial void OnTest_TimeChanging(System.DateTime value);
    partial void OnTest_TimeChanged();
    partial void OnFlagChanging(int value);
    partial void OnFlagChanged();
    partial void OnVoltage_Standard_ValueChanging(float value);
    partial void OnVoltage_Standard_ValueChanged();
    partial void OnNumberChanging(int value);
    partial void OnNumberChanged();
    partial void OnTemperatureChanging(float value);
    partial void OnTemperatureChanged();
    partial void OnStation_AddressChanging(int value);
    partial void OnStation_AddressChanged();
    partial void OnResistance_Standard_ValueChanging(float value);
    partial void OnResistance_Standard_ValueChanged();
    partial void OnOpen_ResistanceChanging(float value);
    partial void OnOpen_ResistanceChanged();
    partial void OnBattery_Serial_NoChanging(string value);
    partial void OnBattery_Serial_NoChanged();
    partial void OnBattery_P1Changing(string value);
    partial void OnBattery_P1Changed();
    partial void OnBattery_P2Changing(string value);
    partial void OnBattery_P2Changed();
    #endregion
		
		public Production_Check()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BatchID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BatchID
		{
			get
			{
				return this._BatchID;
			}
			set
			{
				if ((this._BatchID != value))
				{
					this.OnBatchIDChanging(value);
					this.SendPropertyChanging();
					this._BatchID = value;
					this.SendPropertyChanged("BatchID");
					this.OnBatchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Open_Voltage", DbType="Real NOT NULL")]
		public float Open_Voltage
		{
			get
			{
				return this._Open_Voltage;
			}
			set
			{
				if ((this._Open_Voltage != value))
				{
					this.OnOpen_VoltageChanging(value);
					this.SendPropertyChanging();
					this._Open_Voltage = value;
					this.SendPropertyChanged("Open_Voltage");
					this.OnOpen_VoltageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Test_Time
		{
			get
			{
				return this._Test_Time;
			}
			set
			{
				if ((this._Test_Time != value))
				{
					this.OnTest_TimeChanging(value);
					this.SendPropertyChanging();
					this._Test_Time = value;
					this.SendPropertyChanged("Test_Time");
					this.OnTest_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Int NOT NULL")]
		public int Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Voltage_Standard_Value", DbType="Real NOT NULL")]
		public float Voltage_Standard_Value
		{
			get
			{
				return this._Voltage_Standard_Value;
			}
			set
			{
				if ((this._Voltage_Standard_Value != value))
				{
					this.OnVoltage_Standard_ValueChanging(value);
					this.SendPropertyChanging();
					this._Voltage_Standard_Value = value;
					this.SendPropertyChanged("Voltage_Standard_Value");
					this.OnVoltage_Standard_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
		public int Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Temperature", DbType="Real NOT NULL")]
		public float Temperature
		{
			get
			{
				return this._Temperature;
			}
			set
			{
				if ((this._Temperature != value))
				{
					this.OnTemperatureChanging(value);
					this.SendPropertyChanging();
					this._Temperature = value;
					this.SendPropertyChanged("Temperature");
					this.OnTemperatureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Station_Address", DbType="Int NOT NULL")]
		public int Station_Address
		{
			get
			{
				return this._Station_Address;
			}
			set
			{
				if ((this._Station_Address != value))
				{
					this.OnStation_AddressChanging(value);
					this.SendPropertyChanging();
					this._Station_Address = value;
					this.SendPropertyChanged("Station_Address");
					this.OnStation_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resistance_Standard_Value", DbType="Real NOT NULL")]
		public float Resistance_Standard_Value
		{
			get
			{
				return this._Resistance_Standard_Value;
			}
			set
			{
				if ((this._Resistance_Standard_Value != value))
				{
					this.OnResistance_Standard_ValueChanging(value);
					this.SendPropertyChanging();
					this._Resistance_Standard_Value = value;
					this.SendPropertyChanged("Resistance_Standard_Value");
					this.OnResistance_Standard_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Open_Resistance", DbType="Real NOT NULL")]
		public float Open_Resistance
		{
			get
			{
				return this._Open_Resistance;
			}
			set
			{
				if ((this._Open_Resistance != value))
				{
					this.OnOpen_ResistanceChanging(value);
					this.SendPropertyChanging();
					this._Open_Resistance = value;
					this.SendPropertyChanged("Open_Resistance");
					this.OnOpen_ResistanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery_Serial_No", DbType="NVarChar(50)")]
		public string Battery_Serial_No
		{
			get
			{
				return this._Battery_Serial_No;
			}
			set
			{
				if ((this._Battery_Serial_No != value))
				{
					this.OnBattery_Serial_NoChanging(value);
					this.SendPropertyChanging();
					this._Battery_Serial_No = value;
					this.SendPropertyChanged("Battery_Serial_No");
					this.OnBattery_Serial_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery_P1", DbType="NVarChar(50)")]
		public string Battery_P1
		{
			get
			{
				return this._Battery_P1;
			}
			set
			{
				if ((this._Battery_P1 != value))
				{
					this.OnBattery_P1Changing(value);
					this.SendPropertyChanging();
					this._Battery_P1 = value;
					this.SendPropertyChanged("Battery_P1");
					this.OnBattery_P1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Battery_P2", DbType="NVarChar(50)")]
		public string Battery_P2
		{
			get
			{
				return this._Battery_P2;
			}
			set
			{
				if ((this._Battery_P2 != value))
				{
					this.OnBattery_P2Changing(value);
					this.SendPropertyChanging();
					this._Battery_P2 = value;
					this.SendPropertyChanged("Battery_P2");
					this.OnBattery_P2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
